//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LAVADEROEntities : DbContext
    {
        public LAVADEROEntities()
            : base("name=LAVADEROEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CARGO> CARGOS { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<EMPLEADO> EMPLEADOes { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<FACTURA_SERVICIO> FACTURA_SERVICIO { get; set; }
        public virtual DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public virtual DbSet<PERFIL> PERFILs { get; set; }
        public virtual DbSet<QUEJA_RECLAMO> QUEJA_RECLAMO { get; set; }
        public virtual DbSet<SERVICIO> SERVICIOS { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TIPOVEHICULO> TIPOVEHICULOes { get; set; }
        public virtual DbSet<TURNO> TURNOS { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
        public virtual DbSet<USUARIO_PERFIL> USUARIO_PERFIL { get; set; }
        public virtual DbSet<VEHICULO> VEHICULOes { get; set; }
    
        public virtual int CalcularTotalFactura(Nullable<int> iD_FACTURA)
        {
            var iD_FACTURAParameter = iD_FACTURA.HasValue ?
                new ObjectParameter("ID_FACTURA", iD_FACTURA) :
                new ObjectParameter("ID_FACTURA", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalcularTotalFactura", iD_FACTURAParameter);
        }
    }
}
