//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FACTURA()
        {
            this.FACTURA_SERVICIO = new HashSet<FACTURA_SERVICIO>();
            this.EMPLEADOes = new HashSet<EMPLEADO>();
        }
    
        public int ID_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string FORMA_PAGO { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public string EMPLEADO_ATENCION { get; set; }

        [JsonIgnore]
        public virtual CLIENTE CLIENTE { get; set; }
        [JsonIgnore]
        public virtual FORMA_PAGO FORMA_PAGO1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<FACTURA_SERVICIO> FACTURA_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<EMPLEADO> EMPLEADOes { get; set; }
    }
}
