//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.PROVEEDORES = new HashSet<PROVEEDORE>();
        }
    
        public int ID_PRODUCTO { get; set; }
        public string DESCRIPCION_PRO { get; set; }
        public Nullable<int> TIPO_PRO { get; set; }
        public Nullable<decimal> VALOR_PRODUCTO { get; set; }

        [JsonIgnore]
        public virtual TIPO_PRODUCTO TIPO_PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<PROVEEDORE> PROVEEDORES { get; set; }
    }
}
