//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class QUEJA_RECLAMO
    {
        public int ID_QUEJA { get; set; }
        public string DESCRIPCIÓN_QUEJA { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        [JsonIgnore]
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
