//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PERFIL
    {
        public int id { get; set; }
        public int id_usuario { get; set; }
        public int id_perfil { get; set; }
        public bool activo { get; set; }
        [JsonIgnore]
        public virtual PERFIL PERFIL { get; set; }
        [JsonIgnore]
        public virtual USUARIO USUARIO { get; set; }
    }
}
