//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;


    public partial class VEHICULO
    {
        public string PLACA { get; set; }
        public string MODELO { get; set; }
        public string PROPIETARIO { get; set; }
        public Nullable<int> TIPO { get; set; }

        [JsonIgnore]
        public virtual CLIENTE CLIENTE { get; set; }
        [JsonIgnore]
        public virtual TIPOVEHICULO TIPOVEHICULO { get; set; }
    }
}
