//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public string PLACA { get; set; }
        public string MODELO { get; set; }
        public string PROPIETARIO { get; set; }
        public Nullable<int> TIPO { get; set; }
        [JsonIgnore]
        public virtual CLIENTE CLIENTE { get; set; }
        [JsonIgnore]
        public virtual TIPOVEHICULO TIPOVEHICULO { get; set; }
    }
}
