//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_lavadero.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaFacturaServicio
    {
        public int ID_FACTURA { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CEDULA_CLIENTE { get; set; }
        public string FORMA_PAGO { get; set; }
        public string SERVICIOS { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public string EMPLEADO_ATENCION { get; set; }
    }
}
